# https://blog.nicco.io/2019/08/15/backup-mongodb-inside-of-docker-the-right-way/
- hosts: graylog
  remote_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    volume_name: graylog_journal
    backup_path: /opt/app/backup
  tasks:
  - name: backup_graylog
    docker_container:
      name: backup_container
      image: alpine
      command: tar -cjf /backup/backup_journal.tar.bz2 -C /volume ./
      volumes:
        - "{{ volume_name }}:/volume"
        - "{{ backup_path }}:/backup"
      #docker run --rm -v {{volume_name}}:/volume -v {{backup_path}}:/backup alpine tar -cjf /backup/backup.tar.bz2 -C /volume ./
  - name: backup zu Lokal kopieren
    fetch:
      src: "{{ backup_path }}/backup_journal.tar.bz2"
      dest: "host_backups/{{ inventory_hostname }}"
  - name: backup_mongo
    shell: "cd /opt/app/ && docker-compose exec -T mongodb mongodump --archive --gzip --db graylog > {{backup_path}}/dump.gz"
  - name: backup zu Lokal kopieren
    fetch:
      src: "{{ backup_path }}/dump.gz"
      dest: "host_backups/{{ inventory_hostname }}"