---

- hosts: gitlab
  remote_user: root
  vars_files: terraform_output_vars.yml
  roles:
    - name: common
      floating_ip: "{{ json_terraform_output.gitlab_ip.value.floating }}"
      volume_location: "{{ json_terraform_output.gitlab_ip.value.linux_device }}"
      docker_login: true
    - gitlab
