---

- hosts: graylog
  remote_user: root
  vars:
    json_terraform_output: "{{ lookup('file', 'terraform/output/outputs.json') }}"
  roles:
    - name: common
      floating_ip: "{{ json_terraform_output.floating_ip_address.value }}"
    - graylog
