---

- hosts: graylog
  remote_user: root
  vars:
    #docker_user: "{{ lookup('env','DOCKER_USER') }}"
    #docker_pass:  "{{lookup('env','DOCKER_PASS')}}"
    json_terraform_output: "{{ lookup('file', 'terraform/output/outputs.json') }}"
    graylog_server_ip: "{{ json_terraform_output.graylog_ip.value.server }}"
  tasks:
    - debug: "{{test}}"
  roles:
    - name: common
      floating_ip: "{{ json_terraform_output.graylog_ip.value.floating }}"
      volume_location: "{{ json_terraform_output.graylog_ip.value.linux_device }}"
    - graylog