---

- hosts: graylog
  remote_user: root
  vars:
    json_terraform_output: "{{ lookup('file', 'terraform/output/outputs.json') }}"
  roles:
    - name: common
      floating_ip: "{{ json_terraform_output.graylog_ip.value.floating }}"
      volume_location: "{{ json_terraform_output.graylog_ip.value.linux_device }}"
    - graylog
