local:
  127.0.0.1

monitoring:
  hosts:
    grafana:
      ansible_host: 116.202.179.186
      ansible_user: root

logging:
  hosts:
    graylog:
      ansible_host: "{{graylog_server_ip}}"
      ansible_user: root

registries:
  hosts:
    docker-registry:
      ansible_host: 116.203.66.4
      ansible_user: root
    nexus:
      ansible_host: 78.47.176.75
      ansible_user: root
    gitlab:
      ansible_host: 116.203.99.20
      ansible_user=: root

security:
  hosts:
    keycloak:
      ansible_host: 94.130.151.171
      ansible_user: root

build:
  hosts:
    jenkins:
      ansible_host: 116.203.55.98
      ansible_user: root

quality:
  hosts:
    sonar:
      ansible_host: 78.47.228.104
      ansible_user: root