# https://blog.nicco.io/2019/08/15/backup-mongodb-inside-of-docker-the-right-way/
#https://medium.com/@loomchild/backup-restore-docker-named-volumes-350397b8e362
- hosts: graylog
  remote_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    volume_name: graylog_journal
    backup_path: /opt/app/backup
    json_terraform_output: "{{ lookup('file', '../terraform/output/outputs.json') }}"
    graylog_server_ip: "{{ json_terraform_output.graylog_ip.value.server }}"
  tasks:
  - name: Backup Datei kopieren
    copy:
      src: "../backups/host_backups/{{ inventory_hostname }}{{ backup_path }}/"
      dest: "{{ backup_path }}"
      follow: no
  - name: restore_mongo
    shell: "cd /opt/app/ && docker-compose exec -T mongodb mongorestore --archive --gzip < {{backup_path}}/dump.gz"
  - name: restore_graylog_volume
    docker_container:
      name: backup_container
      image: alpine
      command: "rm -rf /volume/* /volume/..?* /volume/.[!.]* ; tar -C /volume/ -xjf {{backup_path}}/{{volume_name}}.tar.bz2"
      volumes:
        - "{{ volume_name }}:/volume"
        - "{{ backup_path }}:/backup"
