- hosts: gitlab
  remote_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    backup_path: /opt/app/backup
    json_terraform_output: "{{ lookup('file', '../terraform/output/outputs.json') }}"
  vars_files: vars.yml
  tasks:
    - name: unarchive
      unarchive:
        src: "../backups/host_backups/{{ inventory_hostname }}{{ backup_path }}/backup.tar.bz2"
        dest: "/opt/app/gitlab"
