version: '2'
services:
  mongodb:
    image: mongo:4.2.8
    volumes:
      - mongo_data:/data/db
    networks:
      - webproxy
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - webproxy
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.1
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      - VIRTUAL_HOST=logs.ikor.de
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=logs.ikor.de
      - LETSENCRYPT_EMAIL= support@ikor.de
      - GRAYLOG_HTTP_EXTERNAL_URI=https://logs.ikor.de/
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ROOT_PASSWORD_SHA2=5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 #${ADMIN_PW_SHA2}
      - GRAYLOG_PASSWORD_SECRET=password123456789 #${GRAYLOG_PW_SECRET}
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # GELF TCP/UDP, add other ports when necessary
      - 9000:9000
      - 9000:9000/udp
    networks:
      - webproxy

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/data/certs:/etc/nginx/certs:ro
      - ./nginx/data/conf.d:/etc/nginx/conf.d
      - ./nginx/data/vhost.d:/etc/nginx/vhost.d
      - ./nginx/data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webproxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./nginx/data/vhost.d:/etc/nginx/vhost.d
      - ./nginx/data/certs:/etc/nginx/certs:rw
      - ./nginx/data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - webproxy

networks:
  webproxy:

volumes:
  graylog_journal:
  mongo_data:
  es_data: